import PageHeader from "@/components/PageHeader";
import { Card } from "@/components/ui/card";
import ChartCard from "@/components/ChartCard";
import { Line } from "react-chartjs-2";
import { formatCurrency } from "@/data/financialData";
import { useFinancialData } from "@/contexts/FinancialDataContext";
import { useEffect, useState } from "react";

interface MonthlyData {
  months: string[];
  [key: string]: any;
}

interface CESinteticoMensileData {
  progressivo2025?: MonthlyData;
  puntuale2025?: MonthlyData;
  progressivo2024?: MonthlyData;
  puntuale2024?: MonthlyData;
}

type ViewMode = 'progressivo2025' | 'puntuale2025' | 'progressivo2024' | 'puntuale2024';

export default function CESinteticoMensile() {
  const { selectedCompany, getCESinteticoMensileData } = useFinancialData();
  const [ceData, setCeData] = useState<CESinteticoMensileData | null>(null);
  const [viewMode, setViewMode] = useState<ViewMode>('puntuale2025');
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const loadData = async () => {
      if (!selectedCompany) {
        setCeData(null);
        return;
      }

      setLoading(true);
      try {
        const data = await getCESinteticoMensileData(selectedCompany.id);
        if (data && data.length > 0 && data[0].data) {
          setCeData(data[0].data as CESinteticoMensileData);
        } else {
          setCeData(null);
        }
      } catch (error) {
        console.error('Errore nel caricamento dati CE Sintetico Mensile:', error);
        setCeData(null);
      } finally {
        setLoading(false);
      }
    };

    loadData();
  }, [selectedCompany, getCESinteticoMensileData]);

  const handleTabChange = (mode: ViewMode) => {
    setViewMode(mode);
  };

  const currentData = ceData ? ceData[viewMode] : null;

  // Se nessuna azienda è selezionata, mostra un messaggio
  if (!selectedCompany) {
    return (
      <div data-testid="page-ce-sintetico-mensile" className="p-8">
        <PageHeader title="CE Sintetico Mensile" subtitle="Conto Economico Sintetico" />
        <div className="p-8 bg-muted rounded-lg text-center mt-6">
          <p className="text-lg text-muted-foreground">Seleziona un'azienda per visualizzare i dati</p>
        </div>
      </div>
    );
  }

  // Se sta caricando, mostra loading
  if (loading) {
    return <div className="p-8 text-center">Caricamento dati...</div>;
  }

  // Se non ci sono dati, mostra messaggio
  if (!ceData || !currentData) {
    return (
      <div data-testid="page-ce-sintetico-mensile" className="p-8">
        <PageHeader title="CE Sintetico Mensile" subtitle="Dati non disponibili" />
        <div className="p-8 bg-muted rounded-lg text-center mt-6">
          <p className="text-lg text-muted-foreground">Nessun dato disponibile per questa vista ({viewMode}).</p>
        </div>
      </div>
    );
  }

  const { months } = currentData;

  const createRowData = (label: string, values: number[] | undefined, isPercentage = false, isBold = false) => {
    const safeValues = values || [];
    // If no values, return placeholders
    if (safeValues.length === 0) {
      return {
        voce: label,
        values: [],
        total: "n/a",
        isPercentage,
        isBold
      };
    }

    return {
      voce: label,
      values: isPercentage
        ? safeValues.map((v) => `${v.toFixed(1)}%`) // Percentages in excel are usually 0-100 or 0-1? If generated by dashboard logic they are 0-100.
        : safeValues.map((v) => formatCurrency(v).replace("€", "").trim()),
      total: isPercentage
        ? "n/a"
        : formatCurrency(safeValues[safeValues.length - 1] || 0).replace("€", "").trim(), // Last value as 'total' or 'current state' for progressive?
      isPercentage,
      isBold,
    };
  };

  const grossProfit = currentData.grossProfit || [];
  const totaleRicavi = currentData.totaleRicavi || [];

  const marginValues = grossProfit.map((gp: number, i: number) => {
    const ricavi = totaleRicavi[i] || 0;
    return ricavi ? (gp / ricavi) * 100 : 0;
  });

  const data = [
    createRowData("Ricavi caratteristici", currentData.ricaviCaratteristici),
    createRowData("Altri ricavi", currentData.altriRicavi),
    createRowData("TOTALE RICAVI", currentData.totaleRicavi, false, true),
    { voce: "", values: [], total: "", isPercentage: false, isBold: false },
    createRowData("Servizi diretti", currentData.serviziDiretti),
    createRowData("Consulenze dirette", currentData.consulenzeDirette),
    createRowData("Servizi informatici web", currentData.serviziInformatici),
    createRowData("Servizi cloud", currentData.serviziCloud),
    createRowData("COSTI DIRETTI", currentData.costiDiretti, false, true),
    createRowData("Beni strumentali", currentData.beniIndeducibili),
    createRowData("Spese per manutenzione", currentData.speseManutenzione || []),
    createRowData("Altri servizi e prestazioni", currentData.altriServizi),
    createRowData("COSTI INDIRETTI", currentData.costiIndiretti, false, true),
    createRowData("TOTALE COSTI DIRETTI E INDIRETTI", currentData.totaleCostiDirettiIndiretti, false, true),
    createRowData("GROSS PROFIT", currentData.grossProfit, false, true),
    { voce: "", values: [], total: "", isPercentage: false, isBold: false },
    createRowData("Ricavi non tipici", currentData.ricaviNonTipici),
    createRowData("Costi commerciali", currentData.speseCommerciali),
    createRowData("Personale", currentData.personale),
    createRowData("Compensi amministratore", currentData.compensiAmministratore),
    createRowData("Rimborsi amministratore", currentData.rimborsiAmministratore),
    createRowData("Servizi contabili e paghe", currentData.serviziAmministrativi || currentData.serviziContabiliPaghe),
    createRowData("Consulenze legali", currentData.consulenzeLegali),
    createRowData("Consulenze tecniche", currentData.consulenzeTecniche),
    createRowData("Altre spese di funzionamento", currentData.altreSpeseFunzionamento || []),
    createRowData("TOTALE STRUTTURA", currentData.totaleGestioneStruttura || currentData.totaleStruttura, false, true),
    createRowData("EBITDA", currentData.ebitda, false, true),
    { voce: "", values: [], total: "", isPercentage: false, isBold: false },
    createRowData("Ammortamenti e svalutazioni", currentData.totaleAmmortamenti || currentData.ammortamentiSvalutazioni),
    createRowData("Gestione straordinaria", currentData.gestioneStraordinaria),
    createRowData("Gestione finanziaria", currentData.gestioneFinanziaria),
    createRowData("TOTALE ALTRE VOCI NON TIPICHE", currentData.totaleAltreVociNonTipiche || [], false, true),
    createRowData("RISULTATO ANTE IMPOSTE", currentData.ebt || currentData.risultatoAnteImposte, false, true),
    createRowData("Imposte", currentData.imposteDirette || currentData.imposte),
    createRowData("RISULTATO DELL'ESERCIZIO", currentData.risultatoEsercizio || currentData.risultato, false, true),
    { voce: "", values: [], total: "", isPercentage: false, isBold: false },
    {
      voce: "Margine Gross Profit %",
      values: marginValues.map((v: number) => v.toFixed(1) + '%'),
      total: ((currentData.grossProfit?.[currentData.grossProfit.length - 1] / currentData.totaleRicavi?.[currentData.totaleRicavi.length - 1]) * 100).toFixed(1) + '%',
      isPercentage: true,
      isBold: true
    },
  ];

  const totalRows = [2, 8, 12, 13, 25, 31];
  const keyMetricRows = [14, 26, 32];
  const resultRow = [34];

  const trendData = {
    labels: months,
    datasets: [
      {
        label: "Margine Gross Profit %",
        data: marginValues,
        borderColor: "#335C96",
        backgroundColor: "rgba(51, 92, 150, 0.1)",
        tension: 0.4,
      },
    ],
  };

  const chartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { position: "top" as const },
    },
    scales: {
      y: {
        beginAtZero: false,
        ticks: { callback: (value: any) => value + "%" },
      },
    },
  };

  const getTabClass = (mode: ViewMode) => {
    return viewMode === mode
      ? "bg-primary text-primary-foreground shadow px-4 py-2 text-sm font-medium rounded-md transition-colors"
      : "bg-muted text-muted-foreground hover:bg-muted/80 px-4 py-2 text-sm font-medium rounded-md transition-colors";
  };

  return (
    <div data-testid="page-ce-sintetico-mensile" className="space-y-6">
      <div className="bg-primary rounded-lg p-6 text-primary-foreground shadow-lg">
        <h1 className="text-2xl font-bold mb-2">CE Sintetico Mensile</h1>
        <p className="opacity-90">Conto Economico Sintetico - Analisi mensile {viewMode.replace('puntuale', 'Puntuale ')}</p>
      </div>

      <div className="flex flex-wrap gap-2">
        <button onClick={() => handleTabChange('puntuale2025')} className={getTabClass('puntuale2025')}>Puntuale 2025</button>
        <button onClick={() => handleTabChange('puntuale2024')} className={getTabClass('puntuale2024')}>Puntuale 2024</button>
      </div>

      <div className="mb-8">
        <ChartCard title={`Trend Margine Gross Profit Mensile (${viewMode})`}>
          <Line data={trendData} options={chartOptions} />
        </ChartCard>
      </div>

      <Card className="p-6 overflow-x-auto">
        <h3 className="text-lg font-bold mb-5">Riepilogo Mensile Sintetico - {viewMode}</h3>
        <div className="overflow-x-auto">
          <table className="w-full border-collapse min-w-max">
            <thead>
              <tr>
                <th className="bg-muted px-3 py-3 text-sm font-semibold text-muted-foreground border-b-2 border-border text-left sticky left-0 bg-muted z-20 shadow-[2px_0_4px_rgba(0,0,0,0.05)]">
                  Voce
                </th>
                {months.map((month: string) => (
                  <th key={month} className="bg-muted px-3 py-3 text-sm font-semibold text-muted-foreground border-b-2 border-border text-right whitespace-nowrap">
                    {month}
                  </th>
                ))}
                <th className="bg-muted px-3 py-3 text-sm font-semibold text-muted-foreground border-b-2 border-border text-right font-bold">
                  {months[months.length - 1]} (Finale)
                </th>
              </tr>
            </thead>
            <tbody>
              {data.map((row, idx) => {
                if (row.voce === "") {
                  return <tr key={idx}><td colSpan={months.length + 2} className="py-1"></td></tr>;
                }

                const isTotal = totalRows.includes(idx);
                const isKeyMetric = keyMetricRows.includes(idx);
                const isResult = resultRow.includes(idx);

                const rowClassName = isResult
                  ? "bg-yellow-50 dark:bg-yellow-950/20 font-bold"
                  : isKeyMetric
                    ? "bg-blue-100 dark:bg-blue-900/30 font-bold"
                    : isTotal
                      ? "bg-blue-50 dark:bg-blue-950/20 font-bold"
                      : row.isBold
                        ? "font-bold"
                        : "hover:bg-muted/50";

                const cellBg = isResult ? "bg-yellow-50 dark:bg-yellow-950/20" : isKeyMetric ? "bg-blue-100 dark:bg-blue-900/30" : isTotal ? "bg-blue-50 dark:bg-blue-950/20" : "bg-card";

                return (
                  <tr key={idx} className={rowClassName}>
                    <td className={`px-3 py-3 text-sm border-b border-border ${row.isBold ? 'font-semibold' : ''} sticky left-0 z-20 ${cellBg} shadow-[2px_0_4px_rgba(0,0,0,0.05)]`}>
                      {row.voce}
                    </td>
                    {row.values.map((value: string, i: number) => (
                      <td key={i} className="px-3 py-3 text-sm border-b border-border text-right whitespace-nowrap">
                        {row.isPercentage ? value : `€ ${value}`}
                      </td>
                    ))}
                    <td className={`px-3 py-3 text-sm border-b border-border text-right font-bold whitespace-nowrap ${isResult ? 'bg-yellow-100 dark:bg-yellow-900/30' : isKeyMetric ? 'bg-blue-150 dark:bg-blue-800/40' : isTotal ? 'bg-blue-100 dark:bg-blue-900/30' : 'bg-muted/30'}`}>
                      {row.isPercentage ? row.total : `€ ${row.total}`}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
}
